function [v]=compute_rfp_all(am4)
v0=am4.v0; w0=am4.w0; c0=am4.c0; a0=am4.a0; g0=am4.g0; x0=am4.x0;
%TREF
v.tref.v=mean(v0.sfc.tref.ann_stat.mmen.all);
v.tref.w=mean(w0.sfc.tref.ann_stat.mmen.all);
v.tref.c=mean(c0.sfc.tref.ann_stat.mmen.all);
v.tref.a=mean(a0.sfc.tref.ann_stat.mmen.all);
v.tref.g=mean(g0.sfc.tref.ann_stat.mmen.all);
v.tref.x=mean(x0.sfc.tref.ann_stat.mmen.all);

%NETRADTOA
v.netradtoa.v=mean(v0.toa.netrad.ann_stat.mmen.all);
v.netradtoa.w=mean(w0.toa.netrad.ann_stat.mmen.all);
v.netradtoa.c=mean(c0.toa.netrad.ann_stat.mmen.all);
v.netradtoa.a=mean(a0.toa.netrad.ann_stat.mmen.all);
v.netradtoa.g=mean(g0.toa.netrad.ann_stat.mmen.all);
v.netradtoa.x=mean(x0.toa.netrad.ann_stat.mmen.all);
v.netradtoa_clr.v=mean(v0.toa.netrad_clr.ann_stat.mmen.all);
v.netradtoa_clr.w=mean(w0.toa.netrad_clr.ann_stat.mmen.all);
v.netradtoa_clr.c=mean(c0.toa.netrad_clr.ann_stat.mmen.all);
v.netradtoa_clr.a=mean(a0.toa.netrad_clr.ann_stat.mmen.all);
v.netradtoa_clr.g=mean(g0.toa.netrad_clr.ann_stat.mmen.all);
v.netradtoa_clr.x=mean(x0.toa.netrad_clr.ann_stat.mmen.all);
%LWET
v.lwnet.v=mean(v0.toa.lwnet.ann_stat.mmen.all);
v.lwnet.w=mean(w0.toa.lwnet.ann_stat.mmen.all);
v.lwnet.c=mean(c0.toa.lwnet.ann_stat.mmen.all);
v.lwnet.a=mean(a0.toa.lwnet.ann_stat.mmen.all);
v.lwnet.g=mean(g0.toa.lwnet.ann_stat.mmen.all);
v.lwnet.x=mean(x0.toa.lwnet.ann_stat.mmen.all);
v.lwnet_clr.v=mean(v0.toa.lwnet_clr.ann_stat.mmen.all);
v.lwnet_clr.w=mean(w0.toa.lwnet_clr.ann_stat.mmen.all);
v.lwnet_clr.c=mean(c0.toa.lwnet_clr.ann_stat.mmen.all);
v.lwnet_clr.a=mean(a0.toa.lwnet_clr.ann_stat.mmen.all);
v.lwnet_clr.g=mean(g0.toa.lwnet_clr.ann_stat.mmen.all);
v.lwnet_clr.x=mean(x0.toa.lwnet_clr.ann_stat.mmen.all);
%SWET
v.swnet.v=mean(v0.toa.swnet.ann_stat.mmen.all);
v.swnet.w=mean(w0.toa.swnet.ann_stat.mmen.all);
v.swnet.c=mean(c0.toa.swnet.ann_stat.mmen.all);
v.swnet.a=mean(a0.toa.swnet.ann_stat.mmen.all);
v.swnet.g=mean(g0.toa.swnet.ann_stat.mmen.all);
v.swnet.x=mean(x0.toa.swnet.ann_stat.mmen.all);
v.swnet_clr.v=mean(v0.toa.swnet_clr.ann_stat.mmen.all);
v.swnet_clr.w=mean(w0.toa.swnet_clr.ann_stat.mmen.all);
v.swnet_clr.c=mean(c0.toa.swnet_clr.ann_stat.mmen.all);
v.swnet_clr.a=mean(a0.toa.swnet_clr.ann_stat.mmen.all);
v.swnet_clr.g=mean(g0.toa.swnet_clr.ann_stat.mmen.all);
v.swnet_clr.x=mean(x0.toa.swnet_clr.ann_stat.mmen.all);
%LWCF, SWCF, TTCF
v.lwcf.v=mean(v0.toa.lwcf.ann_stat.mmen.all);
v.lwcf.w=mean(w0.toa.lwcf.ann_stat.mmen.all);
v.lwcf.c=mean(c0.toa.lwcf.ann_stat.mmen.all);
v.lwcf.a=mean(a0.toa.lwcf.ann_stat.mmen.all);
v.lwcf.g=mean(g0.toa.lwcf.ann_stat.mmen.all);
v.lwcf.x=mean(x0.toa.lwcf.ann_stat.mmen.all);
v.swcf.v=mean(v0.toa.swcf.ann_stat.mmen.all);
v.swcf.w=mean(w0.toa.swcf.ann_stat.mmen.all);
v.swcf.c=mean(c0.toa.swcf.ann_stat.mmen.all);
v.swcf.a=mean(a0.toa.swcf.ann_stat.mmen.all);
v.swcf.g=mean(g0.toa.swcf.ann_stat.mmen.all);
v.swcf.x=mean(x0.toa.swcf.ann_stat.mmen.all);
v.ttcf.v=mean(v0.toa.ttcf.ann_stat.mmen.all);
v.ttcf.w=mean(w0.toa.ttcf.ann_stat.mmen.all);
v.ttcf.c=mean(c0.toa.ttcf.ann_stat.mmen.all);
v.ttcf.a=mean(a0.toa.ttcf.ann_stat.mmen.all);
v.ttcf.g=mean(g0.toa.ttcf.ann_stat.mmen.all);
v.ttcf.x=mean(x0.toa.ttcf.ann_stat.mmen.all);
%LWP, IWP, TCP
v.lwp.v=mean(v0.atm.lwp.ann_stat.mmen.all);
v.lwp.w=mean(w0.atm.lwp.ann_stat.mmen.all);
v.lwp.c=mean(c0.atm.lwp.ann_stat.mmen.all);
v.lwp.a=mean(a0.atm.lwp.ann_stat.mmen.all);
v.lwp.g=mean(g0.atm.lwp.ann_stat.mmen.all);
v.lwp.x=mean(x0.atm.lwp.ann_stat.mmen.all);
v.iwp.v=mean(v0.atm.iwp.ann_stat.mmen.all);
v.iwp.w=mean(w0.atm.iwp.ann_stat.mmen.all);
v.iwp.c=mean(c0.atm.iwp.ann_stat.mmen.all);
v.iwp.a=mean(a0.atm.iwp.ann_stat.mmen.all);
v.iwp.g=mean(g0.atm.iwp.ann_stat.mmen.all);
v.iwp.x=mean(x0.atm.iwp.ann_stat.mmen.all);
v.wvp.v=mean(v0.atm.wvp.ann_stat.mmen.all);
v.wvp.w=mean(w0.atm.wvp.ann_stat.mmen.all);
v.wvp.c=mean(c0.atm.wvp.ann_stat.mmen.all);
v.wvp.a=mean(a0.atm.wvp.ann_stat.mmen.all);
v.wvp.g=mean(g0.atm.wvp.ann_stat.mmen.all);
v.wvp.x=mean(x0.atm.wvp.ann_stat.mmen.all);

%global
vv=v0.om700.glob; ww=w0.om700.glob; xx=x0.om700.glob;
gg=g0.om700.glob; aa=a0.om700.glob; cc=c0.om700.glob;
[v.lwcf_glob v.swcf_glob v.ttcf_glob]=get_reg_crf(vv,ww,gg,aa,cc,xx,'all');
[v.lwcf_glob_ne v.swcf_glob_ne v.ttcf_glob_ne]=get_reg_crf(vv,ww,gg,aa,cc,xx,'ne');
[v.lwcf_glob_dn v.swcf_glob_dn v.ttcf_glob_dn]=get_reg_crf(vv,ww,gg,aa,cc,xx,'dn');
[v.lwcf_glob_up v.swcf_glob_up v.ttcf_glob_up]=get_reg_crf(vv,ww,gg,aa,cc,xx,'up');
[v.qal_glob v.qam_glob v.qah_glob v.lwp_glob v.iwp_glob v.wvp_glob]=get_reg_cld(vv,ww,gg,aa,cc,xx,'all');
[v.qal_glob_ne v.qam_glob_ne v.qah_glob_ne v.lwp_glob_ne v.iwp_glob_ne v.wvp_glob_ne]=get_reg_cld(vv,ww,gg,aa,cc,xx,'ne');
[v.qal_glob_dn v.qam_glob_dn v.qah_glob_dn v.lwp_glob_dn v.iwp_glob_dn v.wvp_glob_dn]=get_reg_cld(vv,ww,gg,aa,cc,xx,'dn');
[v.qal_glob_up v.qam_glob_up v.qah_glob_up v.lwp_glob_up v.iwp_glob_up v.wvp_glob_up]=get_reg_cld(vv,ww,gg,aa,cc,xx,'up');
%trop
vv=v0.om700.trop; ww=w0.om700.trop; xx=x0.om700.trop;
gg=g0.om700.trop; aa=a0.om700.trop; cc=c0.om700.trop;
[v.lwcf_trop v.swcf_trop v.ttcf_trop]=get_reg_crf(vv,ww,gg,aa,cc,xx,'all');
[v.lwcf_trop_ne v.swcf_trop_ne v.ttcf_trop_ne]=get_reg_crf(vv,ww,gg,aa,cc,xx,'ne');
[v.lwcf_trop_dn v.swcf_trop_dn v.ttcf_trop_dn]=get_reg_crf(vv,ww,gg,aa,cc,xx,'dn');
[v.lwcf_trop_up v.swcf_trop_up v.ttcf_trop_up]=get_reg_crf(vv,ww,gg,aa,cc,xx,'up');
[v.qal_trop v.qam_trop v.qah_trop v.lwp_trop v.iwp_trop v.wvp_trop]=get_reg_cld(vv,ww,gg,aa,cc,xx,'all');
[v.qal_trop_ne v.qam_trop_ne v.qah_trop_ne v.lwp_trop_ne v.iwp_trop_ne v.wvp_trop_ne]=get_reg_cld(vv,ww,gg,aa,cc,xx,'ne');
[v.qal_trop_dn v.qam_trop_dn v.qah_trop_dn v.lwp_trop_dn v.iwp_trop_dn v.wvp_trop_dn]=get_reg_cld(vv,ww,gg,aa,cc,xx,'dn');
[v.qal_trop_up v.qam_trop_up v.qah_trop_up v.lwp_trop_up v.iwp_trop_up v.wvp_trop_up]=get_reg_cld(vv,ww,gg,aa,cc,xx,'up');
%nhet
vv=v0.om700.nhet; ww=w0.om700.nhet; xx=x0.om700.nhet;
gg=g0.om700.nhet; aa=a0.om700.nhet; cc=c0.om700.nhet;
[v.lwcf_nhet v.swcf_nhet v.ttcf_nhet]=get_reg_crf(vv,ww,gg,aa,cc,xx,'all');
[v.lwcf_nhet_ne v.swcf_nhet_ne v.ttcf_nhet_ne]=get_reg_crf(vv,ww,gg,aa,cc,xx,'ne');
[v.lwcf_nhet_dn v.swcf_nhet_dn v.ttcf_nhet_dn]=get_reg_crf(vv,ww,gg,aa,cc,xx,'dn');
[v.lwcf_nhet_up v.swcf_nhet_up v.ttcf_nhet_up]=get_reg_crf(vv,ww,gg,aa,cc,xx,'up');
[v.qal_nhet v.qam_nhet v.qah_nhet v.lwp_nhet v.iwp_nhet v.wvp_nhet]=get_reg_cld(vv,ww,gg,aa,cc,xx,'all');
[v.qal_nhet_ne v.qam_nhet_ne v.qah_nhet_ne v.lwp_nhet_ne v.iwp_nhet_ne v.wvp_nhet_ne]=get_reg_cld(vv,ww,gg,aa,cc,xx,'ne');
[v.qal_nhet_dn v.qam_nhet_dn v.qah_nhet_dn v.lwp_nhet_dn v.iwp_nhet_dn v.wvp_nhet_dn]=get_reg_cld(vv,ww,gg,aa,cc,xx,'dn');
[v.qal_nhet_up v.qam_nhet_up v.qah_nhet_up v.lwp_nhet_up v.iwp_nhet_up v.wvp_nhet_up]=get_reg_cld(vv,ww,gg,aa,cc,xx,'up');
%shet
vv=v0.om700.shet; ww=w0.om700.shet; xx=x0.om700.shet;
gg=g0.om700.shet; aa=a0.om700.shet; cc=c0.om700.shet;
[v.lwcf_shet v.swcf_shet v.ttcf_shet]=get_reg_crf(vv,ww,gg,aa,cc,xx,'all');
[v.lwcf_shet_ne v.swcf_shet_ne v.ttcf_shet_ne]=get_reg_crf(vv,ww,gg,aa,cc,xx,'ne');
[v.lwcf_shet_dn v.swcf_shet_dn v.ttcf_shet_dn]=get_reg_crf(vv,ww,gg,aa,cc,xx,'dn');
[v.lwcf_shet_up v.swcf_shet_up v.ttcf_shet_up]=get_reg_crf(vv,ww,gg,aa,cc,xx,'up');
[v.qal_shet v.qam_shet v.qah_shet v.lwp_shet v.iwp_shet v.wvp_shet]=get_reg_cld(vv,ww,gg,aa,cc,xx,'all');
[v.qal_shet_ne v.qam_shet_ne v.qah_shet_ne v.lwp_shet_ne v.iwp_shet_ne v.wvp_shet_ne]=get_reg_cld(vv,ww,gg,aa,cc,xx,'ne');
[v.qal_shet_dn v.qam_shet_dn v.qah_shet_dn v.lwp_shet_dn v.iwp_shet_dn v.wvp_shet_dn]=get_reg_cld(vv,ww,gg,aa,cc,xx,'dn');
[v.qal_shet_up v.qam_shet_up v.qah_shet_up v.lwp_shet_up v.iwp_shet_up v.wvp_shet_up]=get_reg_cld(vv,ww,gg,aa,cc,xx,'up');

x=v.tref;          x=get_diff(x); v.tref=x;
x=v.netradtoa;     x=get_diff(x); v.netradtoa=x;
x=v.netradtoa_clr; x=get_diff(x); v.netradtoa_clr=x;
x=v.lwnet;         x=get_diff(x); v.lwnet=x;
x=v.lwnet_clr;     x=get_diff(x); v.lwnet_clr=x;
x=v.swnet;         x=get_diff(x); v.swnet=x;
x=v.swnet_clr;     x=get_diff(x); v.swnet_clr=x;
x=v.lwcf;          x=get_diff(x); v.lwcf=x;
x=v.swcf;          x=get_diff(x); v.swcf=x;
x=v.ttcf;          x=get_diff(x); v.ttcf=x;
x=v.lwp;           x=get_diff(x); v.lwp=x;
x=v.iwp;           x=get_diff(x); v.iwp=x;
x=v.wvp;           x=get_diff(x); v.wvp=x;

x=v.lwcf_glob;     x=get_diff(x); v.lwcf_glob=x;
x=v.swcf_glob;     x=get_diff(x); v.swcf_glob=x;
x=v.ttcf_glob;     x=get_diff(x); v.ttcf_glob=x;
x=v.lwcf_glob_ne;  x=get_diff(x); v.lwcf_glob_ne=x;
x=v.swcf_glob_ne;  x=get_diff(x); v.swcf_glob_ne=x;
x=v.ttcf_glob_ne;  x=get_diff(x); v.ttcf_glob_ne=x;
x=v.lwcf_glob_dn;  x=get_diff(x); v.lwcf_glob_dn=x;
x=v.swcf_glob_dn;  x=get_diff(x); v.swcf_glob_dn=x;
x=v.ttcf_glob_dn;  x=get_diff(x); v.ttcf_glob_dn=x;
x=v.lwcf_glob_up;  x=get_diff(x); v.lwcf_glob_up=x;
x=v.swcf_glob_up;  x=get_diff(x); v.swcf_glob_up=x;
x=v.ttcf_glob_up;  x=get_diff(x); v.ttcf_glob_up=x;
x=v.qal_glob;     x=get_diff(x); v.qal_glob=x;
x=v.qam_glob;     x=get_diff(x); v.qam_glob=x;
x=v.qah_glob;     x=get_diff(x); v.qah_glob=x;
x=v.lwp_glob;     x=get_diff(x); v.lwp_glob=x;
x=v.iwp_glob;     x=get_diff(x); v.iwp_glob=x;
x=v.wvp_glob;     x=get_diff(x); v.wvp_glob=x;
x=v.qal_glob_ne;  x=get_diff(x); v.qal_glob_ne=x;
x=v.qam_glob_ne;  x=get_diff(x); v.qam_glob_ne=x;
x=v.qah_glob_ne;  x=get_diff(x); v.qah_glob_ne=x;
x=v.lwp_glob_ne;  x=get_diff(x); v.lwp_glob_ne=x;
x=v.iwp_glob_ne;  x=get_diff(x); v.iwp_glob_ne=x;
x=v.wvp_glob_ne;  x=get_diff(x); v.wvp_glob_ne=x;
x=v.qal_glob_dn;  x=get_diff(x); v.qal_glob_dn=x;
x=v.qam_glob_dn;  x=get_diff(x); v.qam_glob_dn=x;
x=v.qah_glob_dn;  x=get_diff(x); v.qah_glob_dn=x;
x=v.lwp_glob_dn;  x=get_diff(x); v.lwp_glob_dn=x;
x=v.iwp_glob_dn;  x=get_diff(x); v.iwp_glob_dn=x;
x=v.wvp_glob_dn;  x=get_diff(x); v.wvp_glob_dn=x;
x=v.qal_glob_up;  x=get_diff(x); v.qal_glob_up=x;
x=v.qam_glob_up;  x=get_diff(x); v.qam_glob_up=x;
x=v.qah_glob_up;  x=get_diff(x); v.qah_glob_up=x;
x=v.lwp_glob_up;  x=get_diff(x); v.lwp_glob_up=x;
x=v.iwp_glob_up;  x=get_diff(x); v.iwp_glob_up=x;
x=v.wvp_glob_up;  x=get_diff(x); v.wvp_glob_up=x;

%trop
x=v.lwcf_trop;     x=get_diff(x); v.lwcf_trop=x;
x=v.swcf_trop;     x=get_diff(x); v.swcf_trop=x;
x=v.ttcf_trop;     x=get_diff(x); v.ttcf_trop=x;
x=v.lwcf_trop_ne;  x=get_diff(x); v.lwcf_trop_ne=x;
x=v.swcf_trop_ne;  x=get_diff(x); v.swcf_trop_ne=x;
x=v.ttcf_trop_ne;  x=get_diff(x); v.ttcf_trop_ne=x;
x=v.lwcf_trop_dn;  x=get_diff(x); v.lwcf_trop_dn=x;
x=v.swcf_trop_dn;  x=get_diff(x); v.swcf_trop_dn=x;
x=v.ttcf_trop_dn;  x=get_diff(x); v.ttcf_trop_dn=x;
x=v.lwcf_trop_up;  x=get_diff(x); v.lwcf_trop_up=x;
x=v.swcf_trop_up;  x=get_diff(x); v.swcf_trop_up=x;
x=v.ttcf_trop_up;  x=get_diff(x); v.ttcf_trop_up=x;
x=v.qal_trop;     x=get_diff(x); v.qal_trop=x;
x=v.qam_trop;     x=get_diff(x); v.qam_trop=x;
x=v.qah_trop;     x=get_diff(x); v.qah_trop=x;
x=v.lwp_trop;     x=get_diff(x); v.lwp_trop=x;
x=v.iwp_trop;     x=get_diff(x); v.iwp_trop=x;
x=v.wvp_trop;     x=get_diff(x); v.wvp_trop=x;
x=v.qal_trop_ne;  x=get_diff(x); v.qal_trop_ne=x;
x=v.qam_trop_ne;  x=get_diff(x); v.qam_trop_ne=x;
x=v.qah_trop_ne;  x=get_diff(x); v.qah_trop_ne=x;
x=v.lwp_trop_ne;  x=get_diff(x); v.lwp_trop_ne=x;
x=v.iwp_trop_ne;  x=get_diff(x); v.iwp_trop_ne=x;
x=v.wvp_trop_ne;  x=get_diff(x); v.wvp_trop_ne=x;
x=v.qal_trop_dn;  x=get_diff(x); v.qal_trop_dn=x;
x=v.qam_trop_dn;  x=get_diff(x); v.qam_trop_dn=x;
x=v.qah_trop_dn;  x=get_diff(x); v.qah_trop_dn=x;
x=v.lwp_trop_dn;  x=get_diff(x); v.lwp_trop_dn=x;
x=v.iwp_trop_dn;  x=get_diff(x); v.iwp_trop_dn=x;
x=v.wvp_trop_dn;  x=get_diff(x); v.wvp_trop_dn=x;
x=v.qal_trop_up;  x=get_diff(x); v.qal_trop_up=x;
x=v.qam_trop_up;  x=get_diff(x); v.qam_trop_up=x;
x=v.qah_trop_up;  x=get_diff(x); v.qah_trop_up=x;
x=v.lwp_trop_up;  x=get_diff(x); v.lwp_trop_up=x;
x=v.iwp_trop_up;  x=get_diff(x); v.iwp_trop_up=x;
x=v.wvp_trop_up;  x=get_diff(x); v.wvp_trop_up=x;

%nhet
x=v.lwcf_nhet;     x=get_diff(x); v.lwcf_nhet=x;
x=v.swcf_nhet;     x=get_diff(x); v.swcf_nhet=x;
x=v.ttcf_nhet;     x=get_diff(x); v.ttcf_nhet=x;
x=v.lwcf_nhet_ne;  x=get_diff(x); v.lwcf_nhet_ne=x;
x=v.swcf_nhet_ne;  x=get_diff(x); v.swcf_nhet_ne=x;
x=v.ttcf_nhet_ne;  x=get_diff(x); v.ttcf_nhet_ne=x;
x=v.lwcf_nhet_dn;  x=get_diff(x); v.lwcf_nhet_dn=x;
x=v.swcf_nhet_dn;  x=get_diff(x); v.swcf_nhet_dn=x;
x=v.ttcf_nhet_dn;  x=get_diff(x); v.ttcf_nhet_dn=x;
x=v.lwcf_nhet_up;  x=get_diff(x); v.lwcf_nhet_up=x;
x=v.swcf_nhet_up;  x=get_diff(x); v.swcf_nhet_up=x;
x=v.ttcf_nhet_up;  x=get_diff(x); v.ttcf_nhet_up=x;
x=v.qal_nhet;     x=get_diff(x); v.qal_nhet=x;
x=v.qam_nhet;     x=get_diff(x); v.qam_nhet=x;
x=v.qah_nhet;     x=get_diff(x); v.qah_nhet=x;
x=v.lwp_nhet;     x=get_diff(x); v.lwp_nhet=x;
x=v.iwp_nhet;     x=get_diff(x); v.iwp_nhet=x;
x=v.wvp_nhet;     x=get_diff(x); v.wvp_nhet=x;
x=v.qal_nhet_ne;  x=get_diff(x); v.qal_nhet_ne=x;
x=v.qam_nhet_ne;  x=get_diff(x); v.qam_nhet_ne=x;
x=v.qah_nhet_ne;  x=get_diff(x); v.qah_nhet_ne=x;
x=v.lwp_nhet_ne;  x=get_diff(x); v.lwp_nhet_ne=x;
x=v.iwp_nhet_ne;  x=get_diff(x); v.iwp_nhet_ne=x;
x=v.wvp_nhet_ne;  x=get_diff(x); v.wvp_nhet_ne=x;
x=v.qal_nhet_dn;  x=get_diff(x); v.qal_nhet_dn=x;
x=v.qam_nhet_dn;  x=get_diff(x); v.qam_nhet_dn=x;
x=v.qah_nhet_dn;  x=get_diff(x); v.qah_nhet_dn=x;
x=v.lwp_nhet_dn;  x=get_diff(x); v.lwp_nhet_dn=x;
x=v.iwp_nhet_dn;  x=get_diff(x); v.iwp_nhet_dn=x;
x=v.wvp_nhet_dn;  x=get_diff(x); v.wvp_nhet_dn=x;
x=v.qal_nhet_up;  x=get_diff(x); v.qal_nhet_up=x;
x=v.qam_nhet_up;  x=get_diff(x); v.qam_nhet_up=x;
x=v.qah_nhet_up;  x=get_diff(x); v.qah_nhet_up=x;
x=v.lwp_nhet_up;  x=get_diff(x); v.lwp_nhet_up=x;
x=v.iwp_nhet_up;  x=get_diff(x); v.iwp_nhet_up=x;
x=v.wvp_nhet_up;  x=get_diff(x); v.wvp_nhet_up=x;

%shet
x=v.lwcf_shet;     x=get_diff(x); v.lwcf_shet=x;
x=v.swcf_shet;     x=get_diff(x); v.swcf_shet=x;
x=v.ttcf_shet;     x=get_diff(x); v.ttcf_shet=x;
x=v.lwcf_shet_ne;  x=get_diff(x); v.lwcf_shet_ne=x;
x=v.swcf_shet_ne;  x=get_diff(x); v.swcf_shet_ne=x;
x=v.ttcf_shet_ne;  x=get_diff(x); v.ttcf_shet_ne=x;
x=v.lwcf_shet_dn;  x=get_diff(x); v.lwcf_shet_dn=x;
x=v.swcf_shet_dn;  x=get_diff(x); v.swcf_shet_dn=x;
x=v.ttcf_shet_dn;  x=get_diff(x); v.ttcf_shet_dn=x;
x=v.lwcf_shet_up;  x=get_diff(x); v.lwcf_shet_up=x;
x=v.swcf_shet_up;  x=get_diff(x); v.swcf_shet_up=x;
x=v.ttcf_shet_up;  x=get_diff(x); v.ttcf_shet_up=x;
x=v.qal_shet;     x=get_diff(x); v.qal_shet=x;
x=v.qam_shet;     x=get_diff(x); v.qam_shet=x;
x=v.qah_shet;     x=get_diff(x); v.qah_shet=x;
x=v.lwp_shet;     x=get_diff(x); v.lwp_shet=x;
x=v.iwp_shet;     x=get_diff(x); v.iwp_shet=x;
x=v.wvp_shet;     x=get_diff(x); v.wvp_shet=x;
x=v.qal_shet_ne;  x=get_diff(x); v.qal_shet_ne=x;
x=v.qam_shet_ne;  x=get_diff(x); v.qam_shet_ne=x;
x=v.qah_shet_ne;  x=get_diff(x); v.qah_shet_ne=x;
x=v.lwp_shet_ne;  x=get_diff(x); v.lwp_shet_ne=x;
x=v.iwp_shet_ne;  x=get_diff(x); v.iwp_shet_ne=x;
x=v.wvp_shet_ne;  x=get_diff(x); v.wvp_shet_ne=x;
x=v.qal_shet_dn;  x=get_diff(x); v.qal_shet_dn=x;
x=v.qam_shet_dn;  x=get_diff(x); v.qam_shet_dn=x;
x=v.qah_shet_dn;  x=get_diff(x); v.qah_shet_dn=x;
x=v.lwp_shet_dn;  x=get_diff(x); v.lwp_shet_dn=x;
x=v.iwp_shet_dn;  x=get_diff(x); v.iwp_shet_dn=x;
x=v.wvp_shet_dn;  x=get_diff(x); v.wvp_shet_dn=x;
x=v.qal_shet_up;  x=get_diff(x); v.qal_shet_up=x;
x=v.qam_shet_up;  x=get_diff(x); v.qam_shet_up=x;
x=v.qah_shet_up;  x=get_diff(x); v.qah_shet_up=x;
x=v.lwp_shet_up;  x=get_diff(x); v.lwp_shet_up=x;
x=v.iwp_shet_up;  x=get_diff(x); v.iwp_shet_up=x;
x=v.wvp_shet_up;  x=get_diff(x); v.wvp_shet_up=x;

return
