function [vx]=ens_avg_cm4x(v,opt)
  nn=length(v); subnames = fieldnames(v(1));
  for i=1:length(subnames)
    if strcmp(subnames{i},opt)
      opt
      for j=1:nn
	vv(j)=v(j).(subnames{i});
      end
    end
  end
  vx=vv(1);
  for i=2:nn
    vx.id_sum         =vx.id_sum         +vv(i).id_sum;
    vx.frqday         =vx.frqday         +vv(i).frqday;
    vx.prday_av       =vx.prday_av       +vv(i).prday_av;
    vx.prday_idwei    =vx.prday_idwei    +vv(i).prday_idwei;
    vx.prday_idavg    =vx.prday_idavg    +vv(i).prday_idavg;
    vx.prday_idstd    =vx.prday_idstd    +vv(i).prday_idstd;
    vx.prw_av         =vx.prw_av         +vv(i).prw_av;
    vx.prw_idwei      =vx.prw_idwei      +vv(i).prw_idwei;
    vx.prw_idavg      =vx.prw_idavg      +vv(i).prw_idavg;
    vx.prw_idstd      =vx.prw_idstd      +vv(i).prw_idstd;
    vx.lwcf_av        =vx.lwcf_av        +vv(i).lwcf_av;
    vx.lwcf_idwei     =vx.lwcf_idwei     +vv(i).lwcf_idwei;
    vx.lwcf_idavg     =vx.lwcf_idavg     +vv(i).lwcf_idavg;
    vx.lwcf_idstd     =vx.lwcf_idstd     +vv(i).lwcf_idstd;
    vx.swcf_av        =vx.swcf_av        +vv(i).swcf_av   ;
    vx.swcf_idwei     =vx.swcf_idwei     +vv(i).swcf_idwei;
    vx.swcf_idavg     =vx.swcf_idavg     +vv(i).swcf_idavg;
    vx.swcf_idstd     =vx.swcf_idstd     +vv(i).swcf_idstd;
    vx.ttcf_av        =vx.ttcf_av        +vv(i).ttcf_av;
    vx.ttcf_idwei     =vx.ttcf_idwei     +vv(i).ttcf_idwei;
    vx.ttcf_idavg     =vx.ttcf_idavg     +vv(i).ttcf_idavg;
    vx.ttcf_idstd     =vx.ttcf_idstd     +vv(i).ttcf_idstd;
    vx.netradclr_av   =vx.netradclr_av   +vv(i).netradclr_av;
    vx.netradclr_idwei=vx.netradclr_idwei+vv(i).netradclr_idwei;
    vx.netradclr_idavg=vx.netradclr_idavg+vv(i).netradclr_idavg;
    vx.netradclr_idstd=vx.netradclr_idstd+vv(i).netradclr_idstd;
    vx.netrad_av      =vx.netrad_av      +vv(i).netrad_av;
    vx.netrad_idwei   =vx.netrad_idwei   +vv(i).netrad_idwei;
    vx.netrad_idavg   =vx.netrad_idavg   +vv(i).netrad_idavg;
    vx.netrad_idstd   =vx.netrad_idstd   +vv(i).netrad_idstd;
    vx.rlut_av        =vx.rlut_av        +vv(i).rlut_av;
    vx.rlut_idwei     =vx.rlut_idwei     +vv(i).rlut_idwei;
    vx.rlut_idavg     =vx.rlut_idavg     +vv(i).rlut_idavg;
    vx.rlut_idstd     =vx.rlut_idstd     +vv(i).rlut_idstd;
    vx.swabs_av       =vx.swabs_av       +vv(i).swabs_av;
    vx.swabs_idwei    =vx.swabs_idwei    +vv(i).swabs_idwei;
    vx.swabs_idavg    =vx.swabs_idavg    +vv(i).swabs_idavg;
    vx.swabs_idstd    =vx.swabs_idstd    +vv(i).swabs_idstd;
    vx.rlutcs_av      =vx.rlutcs_av      +vv(i).rlutcs_av;
    vx.rlutcs_idwei   =vx.rlutcs_idwei   +vv(i).rlutcs_idwei;
    vx.rlutcs_idavg   =vx.rlutcs_idavg   +vv(i).rlutcs_idavg;
    vx.rlutcs_idstd   =vx.rlutcs_idstd   +vv(i).rlutcs_idstd;
    vx.rsut_av        =vx.rsut_av        +vv(i).rsut_av;
    vx.rsut_idwei     =vx.rsut_idwei     +vv(i).rsut_idwei;
    vx.rsut_idavg     =vx.rsut_idavg     +vv(i).rsut_idavg;
    vx.rsut_idstd     =vx.rsut_idstd     +vv(i).rsut_idstd;
    vx.rsutcs_av      =vx.rsutcs_av      +vv(i).rsutcs_av;
    vx.rsutcs_idwei   =vx.rsutcs_idwei   +vv(i).rsutcs_idwei;
    vx.rsutcs_idavg   =vx.rsutcs_idavg   +vv(i).rsutcs_idavg;
    vx.rsutcs_idstd   =vx.rsutcs_idstd   +vv(i).rsutcs_idstd;
  end
  vx.frqday         =vx.frqday          /nn;
  vx.prday_av       =vx.prday_av        /nn;
  vx.prday_idwei    =vx.prday_idwei     /nn;
  vx.prday_idavg    =vx.prday_idavg     /nn;
  vx.prday_idstd    =vx.prday_idstd     /nn;
  vx.prw_av         =vx.prw_av          /nn;
  vx.prw_idwei      =vx.prw_idwei       /nn;
  vx.prw_idavg      =vx.prw_idavg       /nn;
  vx.prw_idstd      =vx.prw_idstd       /nn;      
  vx.lwcf_av        =vx.lwcf_av         /nn;        
  vx.lwcf_idwei     =vx.lwcf_idwei      /nn;    
  vx.lwcf_idavg     =vx.lwcf_idavg      /nn;    
  vx.lwcf_idstd     =vx.lwcf_idstd      /nn;    
  vx.swcf_av        =vx.swcf_av         /nn;    
  vx.swcf_idwei     =vx.swcf_idwei      /nn;    
  vx.swcf_idavg     =vx.swcf_idavg      /nn;    
  vx.swcf_idstd     =vx.swcf_idstd      /nn;    
  vx.ttcf_av        =vx.ttcf_av         /nn;    
  vx.ttcf_idwei     =vx.ttcf_idwei      /nn;    
  vx.ttcf_idavg     =vx.ttcf_idavg      /nn;    
  vx.ttcf_idstd     =vx.ttcf_idstd      /nn;    
  vx.netradclr_av   =vx.netradclr_av    /nn;  
  vx.netradclr_idwei=vx.netradclr_idwei /nn;
  vx.netradclr_idavg=vx.netradclr_idavg /nn;
  vx.netradclr_idstd=vx.netradclr_idstd /nn;
  vx.netrad_av      =vx.netrad_av       /nn;  
  vx.netrad_idwei   =vx.netrad_idwei    /nn; 
  vx.netrad_idavg   =vx.netrad_idavg    /nn; 
  vx.netrad_idstd   =vx.netrad_idstd    /nn; 
  vx.rlut_av        =vx.rlut_av         /nn; 
  vx.rlut_idwei     =vx.rlut_idwei      /nn; 
  vx.rlut_idavg     =vx.rlut_idavg      /nn; 
  vx.rlut_idstd     =vx.rlut_idstd      /nn; 
  vx.swabs_av       =vx.swabs_av        /nn; 
  vx.swabs_idwei    =vx.swabs_idwei     /nn; 
  vx.swabs_idavg    =vx.swabs_idavg     /nn;
  vx.swabs_idstd    =vx.swabs_idstd     /nn;
  vx.rlutcs_av      =vx.rlutcs_av       /nn;
  vx.rlutcs_idwei   =vx.rlutcs_idwei    /nn;
  vx.rlutcs_idavg   =vx.rlutcs_idavg    /nn;
  vx.rlutcs_idstd   =vx.rlutcs_idstd    /nn;
  vx.rsut_av        =vx.rsut_av         /nn; 
  vx.rsut_idwei     =vx.rsut_idwei      /nn;
  vx.rsut_idavg     =vx.rsut_idavg      /nn; 
  vx.rsut_idstd     =vx.rsut_idstd      /nn;
  vx.rsutcs_av      =vx.rsutcs_av       /nn;
  vx.rsutcs_idwei   =vx.rsutcs_idwei    /nn;
  vx.rsutcs_idavg   =vx.rsutcs_idavg    /nn;
  vx.rsutcs_idstd   =vx.rsutcs_idstd    /nn;
    
return
