function cd=get_cd(v)
[CPD,CPV,CL,RV,RD,LV0,G,ROWL,CPVMCL,EPS,EPSI,GINV,RDOCP,T0,HLF]=thermconst;
plev=[1000 925 850 775 700 600 500 400 300 250 200]; 
k=1; a=1000000;
i=1; cd(i).t=squeeze(mean(v.atm.t1000.sea(k,:,:),1));
i=2; cd(i).t=squeeze(mean(v.atm.t925.sea(k,:,:),1));
i=3; cd(i).t=squeeze(mean(v.atm.t850.sea(k,:,:),1));
i=4; cd(i).t=squeeze(mean(v.atm.t775.sea(k,:,:),1));
i=5; cd(i).t=squeeze(mean(v.atm.t700.sea(k,:,:),1));
i=6; cd(i).t=squeeze(mean(v.atm.t600.sea(k,:,:),1));
i=7; cd(i).t=squeeze(mean(v.atm.t500.sea(k,:,:),1));
i=8; cd(i).t=squeeze(mean(v.atm.t400.sea(k,:,:),1));
i=9; cd(i).t=squeeze(mean(v.atm.t300.sea(k,:,:),1));
i=10;cd(i).t=squeeze(mean(v.atm.t250.sea(k,:,:),1));
i=11;cd(i).t=squeeze(mean(v.atm.t200.sea(k,:,:),1));
i=1; cd(i).qn=squeeze(mean(v.atm.qn1000.sea(k,:,:),1))/a;
i=2; cd(i).qn=squeeze(mean(v.atm.qn925.sea(k,:,:),1))/a;
i=3; cd(i).qn=squeeze(mean(v.atm.qn850.sea(k,:,:),1))/a;
i=4; cd(i).qn=squeeze(mean(v.atm.qn775.sea(k,:,:),1))/a;
i=5; cd(i).qn=squeeze(mean(v.atm.qn700.sea(k,:,:),1))/a;
i=6; cd(i).qn=squeeze(mean(v.atm.qn600.sea(k,:,:),1))/a;
i=7; cd(i).qn=squeeze(mean(v.atm.qn500.sea(k,:,:),1))/a;
i=8; cd(i).qn=squeeze(mean(v.atm.qn400.sea(k,:,:),1))/a;
i=9; cd(i).qn=squeeze(mean(v.atm.qn300.sea(k,:,:),1))/a;
i=10;cd(i).qn=squeeze(mean(v.atm.qn250.sea(k,:,:),1))/a;
i=11;cd(i).qn=squeeze(mean(v.atm.qn200.sea(k,:,:),1))/a;
i=1; cd(i).nn=squeeze(mean(v.atm.nn1000.sea(k,:,:),1));
i=2; cd(i).nn=squeeze(mean(v.atm.nn925.sea(k,:,:),1));
i=3; cd(i).nn=squeeze(mean(v.atm.nn850.sea(k,:,:),1));
i=4; cd(i).nn=squeeze(mean(v.atm.nn775.sea(k,:,:),1));
i=5; cd(i).nn=squeeze(mean(v.atm.nn700.sea(k,:,:),1));
i=6; cd(i).nn=squeeze(mean(v.atm.nn600.sea(k,:,:),1));
i=7; cd(i).nn=squeeze(mean(v.atm.nn500.sea(k,:,:),1));
i=8; cd(i).nn=squeeze(mean(v.atm.nn400.sea(k,:,:),1));
i=9; cd(i).nn=squeeze(mean(v.atm.nn300.sea(k,:,:),1));
i=10;cd(i).nn=squeeze(mean(v.atm.nn250.sea(k,:,:),1));
i=11;cd(i).nn=squeeze(mean(v.atm.nn200.sea(k,:,:),1));
i=1; cd(i).al=squeeze(mean(v.atm.al1000.sea(k,:,:),1));
i=2; cd(i).al=squeeze(mean(v.atm.al925.sea(k,:,:),1));
i=3; cd(i).al=squeeze(mean(v.atm.al850.sea(k,:,:),1));
i=4; cd(i).al=squeeze(mean(v.atm.al775.sea(k,:,:),1));
i=5; cd(i).al=squeeze(mean(v.atm.al700.sea(k,:,:),1));
i=6; cd(i).al=squeeze(mean(v.atm.al600.sea(k,:,:),1));
i=7; cd(i).al=squeeze(mean(v.atm.al500.sea(k,:,:),1));
i=8; cd(i).al=squeeze(mean(v.atm.al400.sea(k,:,:),1));
i=9; cd(i).al=squeeze(mean(v.atm.al300.sea(k,:,:),1));
i=10;cd(i).al=squeeze(mean(v.atm.al250.sea(k,:,:),1));
i=11;cd(i).al=squeeze(mean(v.atm.al200.sea(k,:,:),1));
cd(1).qal    =squeeze(mean(v.atm.qal.sea  (k,:,:),1));
cd(1).qam    =squeeze(mean(v.atm.qam.sea  (k,:,:),1));
cd(1).qah    =squeeze(mean(v.atm.qah.sea  (k,:,:),1));
cd(1).lwp    =squeeze(mean(v.atm.lwp.sea  (k,:,:),1));
cd(1).iwp    =squeeze(mean(v.atm.iwp.sea  (k,:,:),1));
a=0.0;
for k=1:11
  x=cd(k).t; id=(x<a);
  cd(k).ro=100.*plev(k)./(cd(k).t*287); cd(k).ro(id)=NaN;
  cd(k).cn=cd(k).qn.*cd(k).ro;
  x=cd(k).al; id=(x<a);
  cd(k).cn1=cd(k).cn./x; cd(k).cn1(id)=NaN; 
  cd(k).cn2=cd(k).nn./x; cd(k).cn2(id)=NaN; 
end
return
