function x=getflx(vx,nn,opt);
if strcmp(opt,'wmse500')
  i=1;
  FA_wup =vx.r(i).wmse500.avg.FA_wup;
  fa_wup =vx.r(i).wmse500.avg.fa_wup;
  fa_std =vx.r(i).wmse500.std.fa_wup;
  fx_TOT =vx.r(i).wmse500.avg.fx_TOT;
  fx_GRD =vx.r(i).wmse500.avg.fx_GRD;
  fx_edd =vx.r(i).wmse500.avg.fx_edd;
  fx_ed1 =vx.r(i).wmse500.avg.fx_ed1;
  fx_ed2 =vx.r(i).wmse500.avg.fx_ed2;
  fx_ed1a=vx.r(i).wmse500.avg.fx_ed1a;
  fx_ed2a=vx.r(i).wmse500.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).wmse500.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).wmse500.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).wmse500.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).wmse500.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).wmse500.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).wmse500.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).wmse500.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).wmse500.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).wmse500.avg.fx_ed1a];
    fx_ed2a=[fx_ed2a vx.r(i).wmse500.avg.fx_ed2a];
  end
elseif strcmp(opt,'wqt500')
  i=1;
  FA_wup =vx.r(i).wqt500.avg.FA_wup;
  fa_wup =vx.r(i).wqt500.avg.fa_wup;
  fa_std =vx.r(i).wqt500.std.fa_wup;
  fx_TOT =vx.r(i).wqt500.avg.fx_TOT;
  fx_GRD =vx.r(i).wqt500.avg.fx_GRD;
  fx_edd =vx.r(i).wqt500.avg.fx_edd;
  fx_ed1 =vx.r(i).wqt500.avg.fx_ed1;
  fx_ed2 =vx.r(i).wqt500.avg.fx_ed2;
  fx_ed1a=vx.r(i).wqt500.avg.fx_ed1;
  fx_ed2a=vx.r(i).wqt500.avg.fx_ed2;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).wqt500.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).wqt500.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).wqt500.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).wqt500.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).wqt500.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).wqt500.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).wqt500.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).wqt500.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).wqt500.avg.fx_ed1a];
    fx_ed2a=[fx_ed2a vx.r(i).wqt500.avg.fx_ed2a];
  end
elseif strcmp(opt,'whli500')
  i=1;
  FA_wup =vx.r(i).whli500.avg.FA_wup;
  fa_wup =vx.r(i).whli500.avg.fa_wup;
  fa_std =vx.r(i).whli500.std.fa_wup;
  fx_TOT =vx.r(i).whli500.avg.fx_TOT;
  fx_GRD =vx.r(i).whli500.avg.fx_GRD;
  fx_edd =vx.r(i).whli500.avg.fx_edd;
  fx_ed1 =vx.r(i).whli500.avg.fx_ed1;
  fx_ed2 =vx.r(i).whli500.avg.fx_ed2;
  fx_ed1a=vx.r(i).whli500.avg.fx_ed1a;
  fx_ed2a=vx.r(i).whli500.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup vx.r(i).whli500.avg.FA_wup];
    fa_wup =[fa_wup vx.r(i).whli500.avg.fa_wup];
    fa_std =[fa_std vx.r(i).whli500.std.fa_wup];
    fx_TOT =[fx_TOT vx.r(i).whli500.avg.fx_TOT];
    fx_GRD =[fx_GRD vx.r(i).whli500.avg.fx_GRD];
    fx_edd =[fx_edd vx.r(i).whli500.avg.fx_edd];
    fx_ed1 =[fx_ed1 vx.r(i).whli500.avg.fx_ed1];
    fx_ed2 =[fx_ed2 vx.r(i).whli500.avg.fx_ed2];
    fx_ed1a=[fx_ed1 vx.r(i).whli500.avg.fx_ed1a];
    fx_ed2a=[fx_ed2 vx.r(i).whli500.avg.fx_ed2a];
  end
elseif strcmp(opt,'wmse3km')
  i=1;
  FA_wup =vx.r(i).wmse3km.avg.FA_wup;
  fa_wup =vx.r(i).wmse3km.avg.fa_wup;
  fa_std =vx.r(i).wmse3km.std.fa_wup;
  fx_TOT =vx.r(i).wmse3km.avg.fx_TOT;
  fx_GRD =vx.r(i).wmse3km.avg.fx_GRD;
  fx_edd =vx.r(i).wmse3km.avg.fx_edd;
  fx_ed1 =vx.r(i).wmse3km.avg.fx_ed1;
  fx_ed2 =vx.r(i).wmse3km.avg.fx_ed2;
  fx_ed1a=vx.r(i).wmse3km.avg.fx_ed1a;
  fx_ed2a=vx.r(i).wmse3km.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).wmse3km.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).wmse3km.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).wmse3km.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).wmse3km.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).wmse3km.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).wmse3km.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).wmse3km.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).wmse3km.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).wmse3km.avg.fx_ed1];
    fx_ed2a=[fx_ed2a vx.r(i).wmse3km.avg.fx_ed2];
  end
elseif strcmp(opt,'wqt3km')
  i=1;
  FA_wup =vx.r(i).wqt3km.avg.FA_wup;
  fa_wup =vx.r(i).wqt3km.avg.fa_wup;
  fa_std =vx.r(i).wqt3km.std.fa_wup;
  fx_TOT =vx.r(i).wqt3km.avg.fx_TOT;
  fx_GRD =vx.r(i).wqt3km.avg.fx_GRD;
  fx_edd =vx.r(i).wqt3km.avg.fx_edd;
  fx_ed1 =vx.r(i).wqt3km.avg.fx_ed1;
  fx_ed2 =vx.r(i).wqt3km.avg.fx_ed2;
  fx_ed1a=vx.r(i).wqt3km.avg.fx_ed1a;
  fx_ed2a=vx.r(i).wqt3km.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).wqt3km.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).wqt3km.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).wqt3km.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).wqt3km.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).wqt3km.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).wqt3km.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).wqt3km.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).wqt3km.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).wqt3km.avg.fx_ed1a];
    fx_ed2a=[fx_ed2a vx.r(i).wqt3km.avg.fx_ed2a];
  end
elseif strcmp(opt,'whli3km')
  i=1;
  FA_wup =vx.r(i).whli3km.avg.FA_wup;
  fa_wup =vx.r(i).whli3km.avg.fa_wup;
  fa_std =vx.r(i).whli3km.std.fa_wup;
  fx_TOT =vx.r(i).whli3km.avg.fx_TOT;
  fx_GRD =vx.r(i).whli3km.avg.fx_GRD;
  fx_edd =vx.r(i).whli3km.avg.fx_edd;
  fx_ed1 =vx.r(i).whli3km.avg.fx_ed1;
  fx_ed2 =vx.r(i).whli3km.avg.fx_ed2;
  fx_ed1a=vx.r(i).whli3km.avg.fx_ed1a;
  fx_ed2a=vx.r(i).whli3km.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).whli3km.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).whli3km.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).whli3km.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).whli3km.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).whli3km.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).whli3km.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).whli3km.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).whli3km.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).whli3km.avg.fx_ed1a];
    fx_ed2a=[fx_ed2a vx.r(i).whli3km.avg.fx_ed2a];
  end
elseif strcmp(opt,'wqt2km')
  i=1;
  FA_wup =vx.r(i).wqt2km.avg.FA_wup;
  fa_wup =vx.r(i).wqt2km.avg.fa_wup;
  fa_std =vx.r(i).wqt2km.std.fa_wup;
  fx_TOT =vx.r(i).wqt2km.avg.fx_TOT;
  fx_GRD =vx.r(i).wqt2km.avg.fx_GRD;
  fx_edd =vx.r(i).wqt2km.avg.fx_edd;
  fx_ed1 =vx.r(i).wqt2km.avg.fx_ed1;
  fx_ed2 =vx.r(i).wqt2km.avg.fx_ed2;
  fx_ed1a=vx.r(i).wqt2km.avg.fx_ed1a;
  fx_ed2a=vx.r(i).wqt2km.avg.fx_ed2a;
  for i=2:nn
    FA_wup =[FA_wup  vx.r(i).wqt2km.avg.FA_wup];
    fa_wup =[fa_wup  vx.r(i).wqt2km.avg.fa_wup];
    fa_std =[fa_std  vx.r(i).wqt2km.std.fa_wup];
    fx_TOT =[fx_TOT  vx.r(i).wqt2km.avg.fx_TOT];
    fx_GRD =[fx_GRD  vx.r(i).wqt2km.avg.fx_GRD];
    fx_edd =[fx_edd  vx.r(i).wqt2km.avg.fx_edd];
    fx_ed1 =[fx_ed1  vx.r(i).wqt2km.avg.fx_ed1];
    fx_ed2 =[fx_ed2  vx.r(i).wqt2km.avg.fx_ed2];
    fx_ed1a=[fx_ed1a vx.r(i).wqt2km.avg.fx_ed1a];
    fx_ed2a=[fx_ed2a vx.r(i).wqt2km.avg.fx_ed2a];
  end
end

x.FA_wup =FA_wup;
x.fa_wup =fa_wup;
x.fa_std =fa_std;
x.fx_TOT =fx_TOT;
x.fx_GRD =fx_GRD;
x.fx_edd =fx_edd;
x.fx_ed1 =fx_ed1;
x.fx_ed2 =fx_ed2;
x.fx_ed1a=fx_ed1a;
x.fx_ed2a=fx_ed2a;
