function [latx,lonx] = mizborders(sname)

if (strcmp(sname,'Alberta')      | ...
    strcmp(sname,'Saskatchewan') | ...
    strcmp(sname,'Manitoba')     | ...
    strcmp(sname,'Newfoundland  & Labrador') | ...
    strcmp(sname,'Prince Edward Island')     | ...
    strcmp(sname,'Nova Scotia')           | ...
    strcmp(sname,'Northwest Territories') | ...
    strcmp(sname,'Nunavut')          | ...
    strcmp(sname,'Ontario')          | ...
    strcmp(sname,'New Brunswick')    | ...
    strcmp(sname,'Yukon Territory')  | ...
    strcmp(sname,'British Columbia') | ...
    strcmp(sname,'Quebec'))
 
  [latx,lonx]=borders_canada(sname);

else
  
  [latx,lonx]=borders(sname);
  
end

return
