load('/work/miz/mat_pcp/obs/obs_AR_precip.mat'); ar=v;;
load('/work/miz/mat_pcp/obs/obs_TC_precip.mat'); tc=v;
load('/work/miz/mat_pcp/obs/obs_MC_precip.mat'); mc=v;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fig.1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
xl='month'; yl='precipitation (mm/day)'; 
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=9;
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs); legend('boxoff');
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
legend(s1,s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); 
y1=0; y2=3.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=4; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=3.8; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=2.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=3; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=4.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1.8; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=3.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); plot(mon,a,'k'); hold on;
v=ar.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;
v=tc.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=5.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
visfig='off'; figpath='./fig_USA/'; expn='obs'; vname='prday-idwei';
printnew(visfig,figpath,expn,vname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%end of Fig.1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fig.2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
xl='month'; yl='fraction of total precipitation'; 
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=10; 
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.nwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
legend(s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); legend('boxoff');
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.umw; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); 
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.ner; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.wwr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.nrp; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.ovr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.swr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.ssr; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.prday_av   (:,m1:m2); a=nanmean(a,1); a0=a;
v=ar.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'r'); a1=a; hold on;
v=tc.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'g'); a2=a;
v=mc.ser; a=v.prday_idwei(:,m1:m2); a=nanmean(a,1); plot(mon,a./a0,'b'); a3=a;
plot(mon,(a1+a2+a3)./a0,'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
visfig='off'; figpath='./fig_USA/'; expn='obs'; vname='prday-frac';
printnew(visfig,figpath,expn,vname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%end of Fig.2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fig.3%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
xl='month'; yl='fraction of extreme precipitation'; 
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=10;
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
legend(s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); legend('boxoff');
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.umw; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.umw; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ner; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ner; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.wwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.wwr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nrp; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nrp; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ovr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ovr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.swr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.swr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ssr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ssr; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ser; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ser; a=v.prday_fq99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
visfig='off'; figpath='./fig_USA/'; expn='obs'; vname='prday-fq99';
printnew(visfig,figpath,expn,vname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%End of Fig.3%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fig.4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
xl='month'; yl='fraction of extreme precipitation'; 
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=10;
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
legend(s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); legend('boxoff');
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.umw; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.umw; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ner; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ner; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.wwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.wwr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); %xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nrp; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nrp; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ovr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ovr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.swr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.swr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
ylabel(yl,'FontSize',fs); xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ssr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ssr; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ser; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ser; a=v.prday_fq999(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%ylabel(yl,'FontSize',fs); 
xlabel(xl,'FontSize',fs); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
visfig='off'; figpath='./fig_USA/'; expn='obs'; vname='prday-fq99';
printnew(visfig,figpath,expn,vname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=10;
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.nwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
legend(s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=3.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.umw; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.umw; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=4; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.ner; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ner; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=3.8; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.wwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.wwr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=2.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.nrp; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nrp; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=3; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.ovr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ovr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=4.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.swr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.swr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=1.8; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.ssr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ssr; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=3.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a;hold on;
v=tc.ser; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ser; a=v.frqday(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,a1+a2+a3,'k--'); 
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
%y1=0; y2=5.5; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);

visfig='off'; figpath='./fig_USA/'; 
printnew(visfig,figpath,p.expn,p.vname);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s=ar.s; lon=s.lon; lat=s.lat; lm=s.lm0; mon=[1:12]; n=10000;
s1='total'; s2='AR'; s3='TS'; s4='MCS'; loc='northwest';
x1=0.5; x2=12.5; y1=0; y2=5; xy=[x1 x2 y1 y2]; m1=8; m2=19;
pms=[ 0, 0, 1800, 1500]*0.8; row=3; col=3; fs=10;
handle=figure('Position',pms,'visible','on');
subplot(row,col,1); tit='NorthWest';
v=ar.nwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
legend(s2,s3,s4,'AR+TS+MCS','Location','north','FontSize',fs); legend('boxoff');
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,2); tit='Upper Midwest';
v=ar.umw; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.umw; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.umw; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,3); tit='Northeast';
v=ar.ner; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ner; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ner; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,4); tit='West';
v=ar.wwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.wwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.wwr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,5); tit='Northern Rockies and Plains';
v=ar.nrp; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.nrp; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.nrp; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,6); tit='Ohio Valley';
v=ar.ovr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ovr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ovr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,7); tit='SouthWest';
v=ar.swr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.swr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.swr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location','north','FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,8); tit='South';
v=ar.ssr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ssr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ssr; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);
subplot(row,col,9); tit='Southeast';
v=ar.ser; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'r'); a1=a; hold on;
v=tc.ser; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'g'); a2=a;
v=mc.ser; a=v.prday_fp99(:,m1:m2); a=nanmean(a,1); plot(mon,a,'b'); a3=a;
plot(mon,(a1+a2+a3),'k--'); title(tit,'FontSize',fs);
%legend(s1,s2,s3,'Location',loc,'FontSize',fs); title(tit,'FontSize',fs);
y1=0; y2=1; xy=[x1 x2 y1 y2]; axis(xy); set(gca,'FontSize',fs);

visfig='off'; figpath='./fig_USA/'; expn='obs'; vname='prday-fp99';
printnew(visfig,figpath,expn,vname);
