function plot_pattern_effect_Fig_atm_20panel(p)
%let=["(a) ","(b) ","(c) ","(d) ","(e) ","(f) ","(g) ","(h) ","(i) ","(j) "...
%     "(k) ","(l) ","(m) ","(n) ","(o) ","(p) ","(q) ","(r) ","(s) ","(t) "];
let=p.let; %s1=p.s1; s2=p.s2; s3=p.s3; s4=p.s4; s5=p.s5; s6=p.s6;s7=p.s7; s8=p.s8;
lon=p.lon; lat=p.lat; lm=p.lm; co=p.co; len=0.16; wid=0.02;
cmin1=p.cmin1; cmax1=p.cmax1; cmin3=p.cmin3; cmax3=p.cmax3;
cmin4=p.cmin4; cmax4=p.cmax4; cmin7=p.cmin7; cmax7=p.cmax7; cmin10=p.cmin10; cmax10=p.cmax10; 
mk='.'; ms=1; mc=0.1*[1 1 1]; ds=100; cfact=p.cfact; n=5;
a=''; p.unit1_bar=a; p.unit2_bar=a; p.unit3_bar=a; p.unit4_bar=a;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pms=[ 0, 0, 2500, 1300]*1; fsize=9; row=4; col=5; minus=char(8212);
handle = figure('Position', pms,'visible','on'); i=1; unit=p.unit1;
nn=256;  cmap=bluewhitered_miz(nn); colormap(cmap); %colormap(jet); 
subplot(row,col,i); a=p.z1; b=p.dz1; sx=let(i)+p.s1; i=i+1; a1=a; b1=b;
pcolor(lon,lat,a); hold on; shading flat; caxis([cmin1 cmax1]);
if p.do_add;
  add.z=p.z1_add; add.zbin=p.z1_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u1_add; add.ubin=p.u1_addbin; add.v=p.v1_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u1(1:n:end,1:n:end),p.v1(1:n:end,1:n:end),cfact,'y');
%  pcolor(lon,lat,p.tas1); caxis([-3 3]); shading flat; colorbar;
%  [phi psi] = flowfun(lon,lat,p.u1',p.v1'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
contour(lon,lat,p.lm,1,co); axis(p.xy);
s=sprintf('%s (%5.3f%s)',sx,b,p.unit1); s=sprintf('%s',sx); 
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z2; b=p.dz2; sx=let(i)+p.s2; i=i+1; a2=a; b2=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin1 cmax1]);
if p.do_add;
  add.z=p.z1_add; add.zbin=p.z1_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u1_add; add.ubin=p.u1_addbin; add.v=p.v1_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u2(1:n:end,1:n:end),p.v2(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u1',p.v1'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
contour(lon,lat,p.lm,1,co); axis(p.xy);
s=sprintf('%s (%5.3f%s)',sx,b,p.unit1); s=sprintf('%s',sx); 
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z3; b=p.dz3; sx=let(i)+p.s3; i=i+1; a3=a; b3=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin1 cmax1]);
if p.do_add;
  add.z=p.z1_add; add.zbin=p.z1_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u1_add; add.ubin=p.u1_addbin; add.v=p.v1_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u3(1:n:end,1:n:end),p.v3(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u1',p.v1'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
contour(lon,lat,p.lm,1,co); axis(p.xy);
s=sprintf('%s (%5.3f%s)',sx,b,p.unit1); s=sprintf('%s',sx); 
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z4; b=p.dz4; sx=let(i)+p.s4; i=i+1; a4=a; b4=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin1 cmax1]);
if p.do_add;
  add.z=p.z1_add; add.zbin=p.z1_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u1_add; add.ubin=p.u1_addbin; add.v=p.v1_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u4(1:n:end,1:n:end),p.v4(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u1',p.v1'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
contour(lon,lat,p.lm,1,co); axis(p.xy);
s=sprintf('%s (%5.3f%s)',sx,b,p.unit1); s=sprintf('%s',sx); 
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z5; b=p.dz5; sx=let(i)+p.s5; i=i+1; a5=a; b5=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin1 cmax1]);
if p.do_add;
  add.z=p.z1_add; add.zbin=p.z1_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u1_add; add.ubin=p.u1_addbin; add.v=p.v1_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u5(1:n:end,1:n:end),p.v5(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u1',p.v1'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
contour(lon,lat,p.lm,1,co); axis(p.xy);
s=sprintf('%s (%5.3f%s)',sx,b,p.unit1); s=sprintf('%s',sx); 
title(s,'FontSize',fsize,'Interpreter','latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cb0=colorbar('FontSize',fsize,'Location','eastoutside');
set(cb0, 'Position', [0.93 0.765 wid len]); caxis([cmin1, cmax1]); a=0.5;
cb0.Label.String = p.unit1_bar; pos=get(cb0,'Position'); pos
cb0.Label.Position = [pos(1)-0.3 pos(2)+a]; 
cb0.Label.Rotation = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(row,col,i); a=p.u6; b=p.du6; sx=let(i)+p.s6; i=i+1; a4=a; b4=b;n=5;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin4 cmax4]);
contour(lon,lat,lm,1,co); axis(p.xy); [xx,yy] = meshgrid(lon,lat);
if p.do_add
  add.z=p.z6_add; add.zbin=p.z6_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u6_add; add.ubin=p.u6_addbin; add.v=p.v6_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u6(1:n:end,1:n:end),p.v6(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u6',p.v6'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u7; b=p.du7; sx=let(i)+p.s7; i=i+1; a5=a; b5=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin4 cmax4]);
contour(lon,lat,lm,1,co); axis(p.xy)
if p.do_add;
  add.z=p.z6_add; add.zbin=p.z6_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u6_add; add.ubin=p.u6_addbin; add.v=p.v6_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u7(1:n:end,1:n:end),p.v7(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u7',p.v7'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u8; b=p.du8; sx=let(i)+p.s8; i=i+1; a5=a; b5=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin4 cmax4]);
contour(lon,lat,lm,1,co); axis(p.xy)
if p.do_add;
  add.z=p.z6_add; add.zbin=p.z6_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u6_add; add.ubin=p.u6_addbin; add.v=p.v6_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u8(1:n:end,1:n:end),p.v8(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u8',p.v8'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u9; b=p.du9; sx=let(i)+p.s9; i=i+1; a5=a; b5=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin4 cmax4]);
contour(lon,lat,lm,1,co); axis(p.xy)
if p.do_add;
  add.z=p.z6_add; add.zbin=p.z6_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u6_add; add.ubin=p.u6_addbin; add.v=p.v6_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u9(1:n:end,1:n:end),p.v9(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u9',p.v9'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u10; b=p.du10; sx=let(i)+p.s10; i=i+1; a5=a; b5=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin4 cmax4]);
contour(lon,lat,lm,1,co); axis(p.xy)
if p.do_add;
  add.z=p.z6_add; add.zbin=p.z6_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u6_add; add.ubin=p.u6_addbin; add.v=p.v6_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u10(1:n:end,1:n:end),p.v10(1:n:end,1:n:end),cfact,'y');
%  [phi psi] = flowfun(lon,lat,p.u10',p.v10'); %contour(lon,lat,psi',20,'k'); hold on; 
%  contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%  contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cb0=colorbar('FontSize',fsize,'Location','eastoutside');
set(cb0, 'Position', [0.93 0.545 wid len]); caxis([cmin4, cmax4]); a=-0.01;
cb0.Label.String = p.unit3_bar; pos=get(cb0,'Position');
cb0.Label.Position = [pos(1)-0.3 pos(2)+a]; 
cb0.Label.Rotation = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(row,col,i); a=p.u11; b=p.du11; sx=let(i)+p.s11; i=i+1; a7=a; b7=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin7 cmax7]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z11_add; add.zbin=p.z11_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u11_add; add.ubin=p.u11_addbin; add.v=p.v11_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u11(1:n:end,1:n:end),p.v11(1:n:end,1:n:end),cfact,'y');
%   [phi psi] = flowfun(lon,lat,p.u11',p.v11'); %contour(lon,lat,psi',20,'k'); hold on; 
%   contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%   contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u12; b=p.du12; sx=let(i)+p.s12; i=i+1; a8=a; b8=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin7 cmax7]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z11_add; add.zbin=p.z11_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u11_add; add.ubin=p.u11_addbin; add.v=p.v11_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u12(1:n:end,1:n:end),p.v12(1:n:end,1:n:end),cfact,'y');
%   [phi psi] = flowfun(lon,lat,p.u12',p.v12'); %contour(lon,lat,psi',20,'k'); hold on; 
%   contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%   contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u13; b=p.du13; sx=let(i)+p.s13; i=i+1; a8=a; b8=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin7 cmax7]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z11_add; add.zbin=p.z11_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u11_add; add.ubin=p.u11_addbin; add.v=p.v11_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u13(1:n:end,1:n:end),p.v13(1:n:end,1:n:end),cfact,'y');
%   [phi psi] = flowfun(lon,lat,p.u13',p.v13'); %contour(lon,lat,psi',20,'k'); hold on; 
%   contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%   contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u14; b=p.du14; sx=let(i)+p.s14; i=i+1; a8=a; b8=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin7 cmax7]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z11_add; add.zbin=p.z11_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u11_add; add.ubin=p.u11_addbin; add.v=p.v11_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u14(1:n:end,1:n:end),p.v14(1:n:end,1:n:end),cfact,'y');
%   [phi psi] = flowfun(lon,lat,p.u14',p.v14'); %contour(lon,lat,psi',20,'k'); hold on; 
%   contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%   contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.u15; b=p.du15; sx=let(i)+p.s15; i=i+1; a8=a; b8=b;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin7 cmax7]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add
  add.z=p.z11_add; add.zbin=p.z11_addbin; %contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  add.u=p.u11_add; add.ubin=p.u11_addbin; add.v=p.v11_add;
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u15(1:n:end,1:n:end),p.v15(1:n:end,1:n:end),cfact,'y');
%   [phi psi] = flowfun(lon,lat,p.u15',p.v15'); %contour(lon,lat,psi',20,'k'); hold on; 
%   contour(lon,lat,phi', p.phi_bin,p.phi_co,'Linestyle','-', 'showtext','off'); hold on;
%   contour(lon,lat,phi',-p.phi_bin,p.phi_co,'Linestyle','--','showtext','off');
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit3); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cb0=colorbar('FontSize',fsize,'Location','eastoutside');
set(cb0, 'Position', [0.93 0.325 wid len]); caxis([cmin7, cmax7]); a=3.5;%1.2*4;
cb0.Label.String = p.unit3_bar; pos=get(cb0,'Position');
cb0.Label.Position = [pos(1)-0.3 pos(2)+a]; 
cb0.Label.Rotation = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
subplot(row,col,i); a=p.z16; b=p.dz16; sx=let(i)+p.s16; i=i+1; a10=a; b10=b;
add.u=p.u16_add; add.ubin=p.u16_addbin; add.v=p.v16_add;
pcolor(lon,lat,a); hold on; shading flat;  caxis([cmin10 cmax10]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z16_add; add.zbin=p.z16_addbin; add.u=p.u16_add; add.v=p.v16_add;
%  contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u16(1:n:end,1:n:end),p.v16(1:n:end,1:n:end),cfact,'y');
  %contour(lon,lat,p.u16,p.u16_addbin,'y-','showtext',p.show);
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit4); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z17; b=p.dz17; sx=let(i)+p.s17; i=i+1; a11=a; b11=b;
pcolor(lon,lat,a); hold on; shading flat; caxis([cmin10 cmax10]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z16_add; add.zbin=p.z16_addbin; add.u=p.u16_add; add.v=p.v16_add;
%  contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u17(1:n:end,1:n:end),p.v17(1:n:end,1:n:end),cfact,'y');
  %contour(lon,lat,p.u17,p.u16_addbin,'y-','showtext',p.show);
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit4); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z18; b=p.dz18; sx=let(i)+p.s18; i=i+1; a11=a; b11=b;
pcolor(lon,lat,a); hold on; shading flat; caxis([cmin10 cmax10]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z16_add; add.zbin=p.z16_addbin; add.u=p.u16_add; add.v=p.v16_add;
%  contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u18(1:n:end,1:n:end),p.v18(1:n:end,1:n:end),cfact,'y');
%  contour(lon,lat,p.u18,p.u16_addbin,'y-','showtext',p.show);
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit4); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z19; b=p.dz19; sx=let(i)+p.s19; i=i+1; a11=a; b11=b;
pcolor(lon,lat,a); hold on; shading flat; caxis([cmin10 cmax10]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z16_add; add.zbin=p.z16_addbin; add.u=p.u16_add; add.v=p.v16_add;
  contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
  quiver(lon(1:n:end),lat(1:n:end),p.u19(1:n:end,1:n:end),p.v19(1:n:end,1:n:end),cfact,'y');
%  contour(lon,lat,p.u19,p.u16_addbin,'y-','showtext',p.show);
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit4); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
subplot(row,col,i); a=p.z20; b=p.dz20; sx=let(i)+p.s20; i=i+1; a11=a; b11=b;
pcolor(lon,lat,a); hold on; shading flat; caxis([cmin10 cmax10]);
contour(lon,lat,lm,1,co); axis(p.xy);
if p.do_add;
  add.z=p.z16_add; add.zbin=p.z16_addbin; add.u=p.u16_add; add.v=p.v16_add;
%  contour(lon,lat,add.z,add.zbin,p.z1_co,'showtext',p.show);
  contour(lon,lat,add.u, add.ubin,'color',p.z1_co,'Linestyle','-', 'showtext',p.show);
  contour(lon,lat,add.u,-add.ubin,'color',p.z1_co,'Linestyle','--','showtext',p.show);
  quiver(lon(1:n:end),lat(1:n:end),add.u(1:n:end,1:n:end),add.v(1:n:end,1:n:end),cfact,'k');
%  quiver(lon(1:n:end),lat(1:n:end),p.u20(1:n:end,1:n:end),p.v20(1:n:end,1:n:end),cfact,'y');
%  contour(lon,lat,p.u20,p.u16_addbin,'y-','showtext',p.show);
end;
s=sprintf('%s (%5.3f%s)',sx,b,p.unit4); s=sprintf('%s',sx);
title(s,'FontSize',fsize,'Interpreter','latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
cb0=colorbar('FontSize',fsize,'Location','eastoutside');
set(cb0, 'Position', [0.93 0.106 wid len]); caxis([cmin10 cmax10]); a=3.8; %1.25*4;
cb0.Label.String = p.unit4_bar; pos=get(cb0,'Position');
cb0.Label.Position = [pos(1)-0.3 pos(2)+a]; 
cb0.Label.Rotation = 0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%cb=colorbar('FontSize',fsize+2,'Location','southoutside');
%set(cb, 'Position', [.165 .04 .7 .02]); caxis([cmin1, cmax1]); 
%cb.Label.String = p.unit_bar; %title(cb, unit,'FontSize',fsize+2);
%pos=get(cb,'Position')
%cb.Label.Position = [pos(1)/2+p.pos1 pos(2)+1.7];  %for radiation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%nn=256;  cmap=bluewhitered_miz(nn); colormap(cmap);
%nn=256; cmap=cbrewer('div','BrBG',nn); colormap(cmap);
%nn=256; cmap=cbrewer('div','Spectral',nn); colormap(cmap);
%nn=256; cmap=cbrewer('seq','Greens',nn); colormap(cmap);
%expn='cm4_spear_climsen'; visfig='off'; figpath='./fig_gclimsen/';
expn='pattern_effect'; visfig='off'; figpath='./fig_land/';
printnew(visfig,figpath,expn,p.vname);
return
